// Package report generates output formats (JSON, Markdown)
package report

import (
	"encoding/json"
	"fmt"
	"os"
	"text/template"
	"time"
)

// DiagnosticResult aggregates all diagnostic data
type DiagnosticResult struct {
	Timestamp    time.Time `json:"timestamp"`
	Interfaces   []string  `json:"interfaces"`
	DurationSecs int       `json:"duration_seconds"`
	TCPStats     struct {
		SynSent     int     `json:"syn_sent"`
		SynAckRcvd  int     `json:"syn_ack_received"`
		RstRcvd     int     `json:"rst_received"`
		SynAckRatio float64 `json:"syn_ack_ratio_percent"`
	} `json:"tcp_handshake"`
	ConntrackCounters struct {
		Total       int `json:"total"`
		Established int `json:"established"`
		SynSent     int `json:"syn_sent"`
		Unreplied   int `json:"unreplied"`
		Other       int `json:"other"`
	} `json:"conntrack"`
	PacketsCaptured int `json:"packets_captured"`
	Summary         string `json:"summary"`
	Recommendation  string `json:"recommendation"`
}

// ToJSON writes diagnostic result as JSON
func ToJSON(r *DiagnosticResult, path string) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return fmt.Errorf("json.MarshalIndent: %w", err)
	}
	return os.WriteFile(path, data, 0644)
}

// markdownTmpl defines the Markdown report template
const markdownTmpl = `# Network Diagnostics Report
**Generated:** {{ .Timestamp.Format "2006-01-02 15:04:05" }}

## Overview
- **Interfaces:** {{ .Interfaces }}
- **Duration:** {{ .DurationSecs }} seconds
- **Packets Captured:** {{ .PacketsCaptured }}

## TCP Handshake Analysis
| Metric | Value |
|--------|-------|
| SYN Sent | {{ .TCPStats.SynSent }} |
| SYN-ACK Received | {{ .TCPStats.SynAckRcvd }} |
| RST Received | {{ .TCPStats.RstRcvd }} |
| SYN-ACK Ratio | {{ printf "%.1f" .TCPStats.SynAckRatio }}% |

## Connection Tracking
| State | Count |
|-------|-------|
| Established | {{ .ConntrackCounters.Established }} |
| SYN_SENT | {{ .ConntrackCounters.SynSent }} |
| UNREPLIED | {{ .ConntrackCounters.Unreplied }} |
| Other | {{ .ConntrackCounters.Other }} |

## Summary
{{ .Summary }}

## Recommendation
{{ .Recommendation }}

---
*Generated by network-app*
`

func init() {
	template.Must(template.New("report").Funcs(template.FuncMap{"join": stringsJoin}).Parse(markdownTmpl))
}

func stringsJoin(a []string, sep string) string {
	if len(a) == 0 {
		return ""
	}
	result := a[0]
	for i := 1; i < len(a); i++ {
		result += sep + a[i]
	}
	return result
}

// ToMarkdown writes diagnostic result as Markdown
func ToMarkdown(r *DiagnosticResult, path string) error {
	tmpl, err := template.New("report").Parse(markdownTmpl)
	if err != nil {
		return fmt.Errorf("template.Parse: %w", err)
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("os.Create: %w", err)
	}
	defer f.Close()
	return tmpl.Execute(f, r)
}